function profile=prof_circle(d,r,n,t)
phi=linspace(0,2*pi,n);
%profile.x=d./2.*cos(phi)+(0.5.*d);
profile.x=d./2.*cos(phi)+t.*d;
profile.y=d./2.*sin(phi);
profile.z=ones(1,n)*r;
profile.Cd=0.43;
profile.Cl=0;
profile.camber=d;
profile.alpha_bau=0;
profile.r=r;
profile.name=join(['circle ',num2str(d),' m']);
